# files that are already highly compressed (zim, videos) will probably
# transfer faster without the -z option (which uses zip compression)
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-kalite /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-afristory /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-ck12 /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-file_share /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-GCF2015 /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-ebooks /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-hesperian_health /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-infonet /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-local_content /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-math_expression /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-asst_medical /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-medline_plus /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-scratch /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-musictheory /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-olpc /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-practical_action /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-understanding_algebra /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-PhET /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-radiolab /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-powertyping /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-iicba /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikibooks /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikipedia_for_schools /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikisource /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikiversity /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikivoyage /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wiktionary /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-windows_apps /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-worldmap /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-wikipedia /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-oya /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-law_library /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-fantastic_phonics /media/RACHEL/rachel/modules/
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-scale-of-universe /media/RACHEL/rachel/modules/
rsync -Pav  rsync://dev.worldpossible.org/rachelmods/en-TED /media/RACHEL/rachel/modules/
