sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-afristory /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-ck12 /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-file_share /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-GCF2015 /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-ebooks /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-hesperian_health /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-infonet /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-math_expression /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-asst_medical /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-medline_plus /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-scratch /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-musictheory /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-olpc /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-practical_action /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-understanding_algebra /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-iicba /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wikibooks /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wikipedia_for_schools /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wikiversity /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wikivoyage /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wiktionary /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-windows_apps /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-worldmap /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-kalite /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/en-wikipedia /media/RACHEL/rachel/modules/.

