sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-ap_didact /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-bibliofilo /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-biblioteca /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-blockly_games /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-cnbguatemala /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-ebooks /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-educalab /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-GCF2015 /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-guatemala /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-guias /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-hesperian_health /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-kalite /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-medline_plus /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-soluciones /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-vedoque /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-wikibooks /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-wikihow /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-wikipedia /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-wikivoyage /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-wiktionary /media/RACHEL/rachel/modules/.
sudo rsync -Pavz rsync://192.168.1.74/rachelmods/modules/es-windows_apps /media/RACHEL/rachel/modules/.
echo "you must move ka-lite content from /media/RACHEL/rachel/modules/en-kalite/content/* to /media/RACHEL/kacontent/. " 
