rsync -Pavz rsync://dev.worldpossible.org/rachelmods/biblioteca-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/guatemala-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/guias_es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/vedoque-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/medline_plus-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/hesperian_health-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/wikipedia_es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/ebooks-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/soluciones_es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/wikihow-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/ap_didact_es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/cnbguatemala-es /var/www/modules/.
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/file_share-es /var/www/modules/.
