sudo rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-afristory /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-ck12 /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-file_share /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-GCF2015 /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-ebooks /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-hesperian_health /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-infonet /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-math_expression /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-asst_medical /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-medline_plus /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-scratch /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-musictheory /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-olpc /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-practical_action /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-understanding_algebra /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-iicba /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-wikibooks /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-wikipedia_for_schools /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-wikiversity /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-wikivoyage /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-wiktionary /var/www/modules
rsync -Pavz rsync://dev.worldpossible.org/rachelmods/fr-windows_apps /var/www/modules
